name: Unity Build & Artifact

on:
  push:
    branches:
      - main  # or your main development branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: StandaloneLinux64  # Change as needed
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnityBuild
          path: build/StandaloneLinux64/  # Adjust path to match your build output
